// Narrative drawn from the project READMEs, published reports and local pipelines.
// Sources are shown in each story. Proposed work is distinguished from results.
export const stories = {
  matrix: {
    type:'Dissertation / comparative experiment',
    built:'I prepared Environment Agency monitoring data in Python and benchmarked four regression models across five water-quality targets, using IBM SPSS Modeler in the modelling workflow and Power BI to present the results.',
    why:'Which model works best depends on what it is predicting. This study holds the inputs, chronological split and evaluation metrics consistent within each target to compare four model families fairly.',
    outputs:['Cleaned, wide-format datasets for five targets','20 model–target comparisons with R², RMSE and MAE','Report, comparison plots and an interactive Power BI dashboard'],
    decisions:[['Preserve temporal order','Training uses 2000–2017; testing uses 2018–2025. This measures performance on later observations. The models use other water measurements from each observation, so this is not a lag-only forecast.'],['Use measurements and calendar features','Each target is predicted from the other four selected water-quality parameters plus year, month and day. Each target retains its own valid records; sample counts differ across targets.'],['Respect detection limits','Values marked < or > are treated as missing rather than exact numbers. Data is filtered to five parameters and reshaped from long to wide before modelling.'],['Keep a baseline','Ridge provides a regularised linear reference against Random Forest, MLP and XGBoost. More complexity must be justified by the measured results.']],
    findings:[['Strongest result','XGBoost reaches R² 0.785 on water temperature and leads on four of the five targets. Random Forest also performs well on temperature at 0.729.'],['An informative failure','All four BOD R² scores are negative. Ridge has the highest BOD R² at −0.007, while XGBoost has the lowest BOD MAE. Different metrics reveal different aspects of error.'],['Data preparation needed care','I renamed the files manually and spotted my own mistake: the Thames 2000 and 2001 filenames were swapped. I corrected them before constructing the final dataset.']],
    next:'The inputs exclude site and area context, rainfall, river flow, land use and discharge. Future work could add these variables, tune models per target and use further time-preserving evaluation. These are recommendations, not completed improvements.',
    source:'https://github.com/nawafbalmutairi/ml-water-quality-benchmark',
  },
  kpis:{
    type:'Academic BI solution / illustrative data',
    built:'I built a Power BI report for H100 and H200 supply-chain analysis, supported by a star-schema model, eight DAX measures, six headline KPIs and a systems-thinking study.',
    why:'Backorders, spare capacity and on-time delivery can tell different stories. The project connects the numbers to foundry and packaging constraints so a viewer can ask where fulfilment is breaking down.',
    outputs:['Power BI report with product and region slicers','Star-schema model and eight DAX measures','Rich picture, causal loops and Balanced Scorecard'],
    decisions:[['Map the system before the dashboard','The rich picture identifies upstream suppliers, planning teams and downstream customers. Causal loops connect demand pressure, forecast volatility, capacity and lead time.'],['Make measures reusable','Product, region and time organise the analytical model. DAX measures and cross-filtering let the same report answer several operational questions.'],['Separate error measures','Forecast accuracy uses aggregate absolute error relative to total demand; MAPE averages percentage errors. Their different weighting means 96.4% and 24.3% should not be treated as complements.']],
    findings:[['Forecasting needs context','The report describes a May/November pattern in forecast versus actual demand. Fiscal timing is a hypothesis to investigate, not a proven causal explanation.'],['Capacity is not fulfilment','57% utilisation alongside 42.3K backorders prompts a bottleneck investigation. It does not establish that adding production capacity would clear the queue.'],['Connect measures to decisions','Lead time and on-time delivery describe customer-facing service; backorders and forecast error help explain the pressure behind it.']],
    next:'The repository identifies the data as synthetic / illustrative. These are academic report values, not verified NVIDIA operating results or evidence of a deployed production integration.',
    source:'https://github.com/nawafbalmutairi/nvidia-supply-chain-bi',
  },
  versus:{
    type:'Azure ML Designer / controlled image-classification study',
    built:'I built training and inference pipelines in Azure ML Designer to compare DenseNet and ResNet on a small, labelled facial-image classification task.',
    why:'Changing preprocessing and architecture together would make the results difficult to interpret. The study keeps the transformation workflow consistent and changes the network.',
    outputs:['GPU-based PyTorch training pipeline','Separate inference pipeline for 30 unseen images','Precision, recall and accuracy for four configurations'],
    decisions:[['One preparation path','Images are converted to an Azure Image Directory. The same initialised transformation is applied across training, validation and test inputs.'],['Separate training from inference','The training workflow uses 100 images and nested 70/30 splits. The inference workflow reuses trained weights on a separately curated 30-image set.'],['Compare more than one score','Precision, recall and accuracy are recorded for each architecture in both evaluation modes.']],
    findings:[['DenseNet leads both comparisons','Reported accuracy is 80% versus 73.33% in the training-pipeline evaluation, and 86.67% versus 80% on the unseen inference set.'],['Different sets, different difficulty','The higher inference score is not a before/after improvement on the same examples. The two evaluation sets can differ in difficulty.'],['A small study, not a universal winner','Thirty unseen images are too few to establish broad performance. Matching aggregate scores also does not, by itself, demonstrate fairness across groups.']],
    next:'A larger, more diverse independent evaluation and class-level error analysis would be needed before making wider claims. The project measures dataset labels; it does not establish a person’s gender identity.',
    source:'https://github.com/nawafbalmutairi/ai-face-recognition',
  },
  blueprint:{
    type:'Coursework / full-stack conference platform',
    built:'I built a PHP and MySQL conference-information platform with browser pages, administrative CRUD operations and a JSON REST API.',
    why:'Conference information needs to be browsable by attendees and maintainable by administrators. Programmatic access lets other clients retrieve the same information through a defined interface.',
    outputs:['Conference listing and detail pages','Session-based administration','Five documented REST operations'],
    decisions:[['Separate reading and editing','Public users can retrieve conference information. Creating, updating and deleting records require authentication.'],['Use a relational store','MySQL provides persistent conference data for both the PHP pages and API consumers.'],['Define an explicit API contract','HTTP methods distinguish listing, retrieval, creation, updates and deletion. JSON responses and status codes communicate the outcome.']],
    findings:[['One platform, two access paths','The browser interface supports people; REST endpoints support software clients.'],['End-to-end engineering','The documented scope spans frontend pages, PHP request handling, session authentication and relational persistence.']],
    next:'The portfolio also records a Kruchten 4+1 architecture study. The walkthrough below describes the documented PHP/MySQL application; a verified live Kubernetes deployment is not established by the available source.',
    source:'https://github.com/nawafbalmutairi/Conference-Info-Platform',
  },
  analytics:{
    type:'Data analysis / US furniture transactions',
    built:'I built a data-cleaning and analysis workflow for 2,121 furniture transactions, then presented trends, discount relationships and geographic performance in an interactive Chart.js report.',
    why:'Revenue alone can hide losses. The study asks when the business sells, which discounts coincide with losses, and which states generate profit rather than just volume.',
    outputs:['Dataset profile across 21 columns and 48 months','Missing-data treatment and descriptive statistics','Time, discount and state-level analytical views'],
    decisions:[['Inspect the distribution first','Sales are right-skewed: mean $355.03 versus median $183.97. Looking at both prevents a few expensive orders from defining a typical transaction.'],['Make cleaning visible','The report records 106 missing Sales values and 106 missing Discount values, followed by mean imputation. This preserves the available mean but can reduce variance and change relationships.'],['Pair revenue with profit','Monthly, regional and state comparisons include both measures so that high sales cannot conceal a negative margin.']],
    findings:[['Discounts can erase the margin','The published report shows $55.5K profit from 787 zero-discount orders versus a $23.6K loss from 207 orders in the 41–70% discount band.'],['High sales can conceal losses','Texas records about $58K revenue and a $9.7K loss; Washington records about $48K revenue and $7.2K profit.'],['Timing matters','Q4 revenue peaks recur across the four-year period. The report recommends aligning inventory and campaigns with the seasonal rise while monitoring margins.']],
    next:'The report describes associations, not a controlled test of discount causality. Imputed data, product mix and state-level costs should be considered before turning a pattern into a pricing policy.',
    source:'https://nawafbalmutairi.github.io/furniture-sales-dashboard/',
  },
  register:{
    type:'ITIL 4 / proposed CMDB implementation strategy',
    built:'I designed a configuration-management strategy for an 87-store retail case study: a CMDB information model, ownership rules, an eight-phase rollout and seven success measures.',
    why:'Store POS, warehouse systems, ERP and e-commerce operate in silos. Without a dependable asset-and-relationship view, support teams cannot confidently assess an incident or the impact of a change.',
    outputs:['CI attributes and relationship model','Eight-phase implementation and governance plan','Risk assessment, responsibilities and KPI targets'],
    decisions:[['Record relationships, not just equipment','A useful CMDB connects a configuration item to services, locations, owners and dependencies. That makes it useful during change assessment.'],['Give the records owners','Discovery tools can find assets, but validation, update procedures and named ownership are needed to prevent the data becoming stale.'],['Pilot before national rollout','The proposed plan starts with a small store group and one distribution centre, then uses feedback before expanding.']],
    findings:[['Change planning','A proposed POS upgrade should be assessed against network, payment and peripheral dependencies before approval.'],['Incident diagnosis','Service-desk staff need the affected CI’s version and connected services to narrow the investigation.'],['Success must be measured','CI accuracy above 95%, completeness above 90% and a 20% incident-resolution improvement are proposed targets, not measured rollout results.']],
    next:'This deliverable is an implementation strategy for a retail case study. It does not report a completed CMDB deployment or achieved business improvements.',
    source:'https://nawafbalmutairi.github.io/ITIL-Configuratio-Management-Abona-Tarn-PLC/index.html',
  },
  screens:{
    type:'Human-computer interaction / evaluated prototype',
    built:'I designed a student work-life planning concept through personas, MoSCoW requirements, six interface sketches, a wireflow, a Figma prototype and a cognitive walkthrough.',
    why:'Working students juggle shifts, classes and deadlines. The design aims to put commitments in one place and make planning understandable without adding another complicated tool.',
    outputs:['Three personas and prioritised requirements','Six-screen concept and connected wireflow','Nine-task cognitive walkthrough with identified failures'],
    decisions:[['Start with conflicting commitments','Sarah, James and Alex represent schedule conflicts, unpredictable work and limited study time. Their goals inform the calendar, task and reminder requirements.'],['Prioritise the essential journey','Scheduling, calendar, reminders and personalised recommendations are Must requirements; progress tracking, time blocking and offline access are Should requirements.'],['Evaluate the action, not just the screen','The walkthrough checks whether someone knows what to do, sees how, understands the next step and receives feedback.']],
    findings:[['Five flows passed all four checks','Login, add task, set reminder, calendar view and logout passed the reported walkthrough questions.'],['Editing was the clearest failure','Task editing failed three of four checks: the entry point, form and save/edit action were unclear.'],['Feedback was missing','Priority/date changes, progress tracking and profile editing lacked clear confirmation after the action.']],
    next:'The next iteration should make Edit discoverable and add explicit save/updated feedback, then repeat the walkthrough. This is a prototype study, not a shipped productivity app; those fixes are recommendations.',
    source:'https://nawafbalmutairi.github.io/UCD-Practical-Work-Work-Life-Balance-App/index.html',
  },
  dials:{
    type:'Power BI / public-sector indicator study',
    built:'I created a Power BI study of Saudi Vision 2030 indicators, using DAX and a dashboard presentation shared through LinkedIn.',
    why:'The project brings a business-intelligence approach to public-sector progress: organise indicators into a readable view rather than leaving them as disconnected figures.',
    outputs:['Public-sector KPI presentation','Power BI and DAX workflow','Published project reference'],
    decisions:[['Keep indicator context visible','Understanding an indicator requires its definition, reporting period and reference point. These are the details a complete walkthrough should expose.']],
    findings:[['Documented scope','The available portfolio identifies the subject and tools. It does not contain the indicator series, calculation definitions or result values.']],
    next:'The original dashboard or report is needed to add an accurate indicator-by-indicator walkthrough. No national progress scores or project outcomes are invented here.',
    source:'https://www.linkedin.com/in/nawaf-almutairi-907766290/',
  },
  commits:{
    type:'Portfolio / collection of independent projects',
    built:'I maintain a public collection spanning data analysis, machine learning, business intelligence, architecture and IT service management.',
    why:'A portfolio should let someone move from a claim to the work behind it. Each project provides a different view of how I frame problems, build systems and explain results.',
    outputs:['Project repositories and documentation','Interactive portfolio and case studies','Source links for further exploration'],
    decisions:[['Organise around the problem','Projects are grouped by the kind of question they answer, not just the language or tool used.'],['Make the evidence accessible','The portfolio links to reports and repositories so a viewer can inspect the work behind a diagram or headline.']],
    findings:[['A range of deliverables','The collection includes experiments, BI reports, a web platform, a design prototype and a service-management strategy. Their outcomes are described according to their scope.']],
    next:'Each repository has its own scope and documentation. The collection is ongoing; repository count alone is not a measure of completeness or quality.',
    source:'https://github.com/nawafbalmutairi',
  },
};
